In [1]:
pip install dask

Requirement already satisfied: dask in c:\users\esire\anaconda3\lib\site-packages (2022.7.0)
Requirement already satisfied: toolz>=0.8.2 in c:\users\esire\anaconda3\lib\site-packages (from dask) (0.12.0)
Requirement already satisfied: packaging>=20.0 in c:\users\esire\anaconda3\lib\site-packages (from dask) (22.0)
Requirement already satisfied: fsspec>=0.6.0 in c:\users\esire\anaconda3\lib\site-packages (from dask) (2022.11.0)
Requirement already satisfied: cloudpickle>=1.1.1 in c:\users\esire\anaconda3\lib\site-packages (from dask) (2.0.0)
Requirement already satisfied: pyyaml>=5.3.1 in c:\users\esire\anaconda3\lib\site-packages (from dask) (6.0)
Requirement already satisfied: partd>=0.3.10 in c:\users\esire\anaconda3\lib\site-packages (from dask) (1.2.0)
Requirement already satisfied: locket in c:\users\esire\anaconda3\lib\site-packages (from partd>=0.3.10->dask) (1.0.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import dask.array as da

In [3]:
images = da.ones((10000, 1000, 1000))
images

dask.array<ones_like, shape=(10000, 1000, 1000), dtype=float64, chunksize=(250, 250, 250), chunktype=numpy.ndarray>

In [8]:
import dask
import dask.dataframe as dd  # For large DataFrame operations
from dask.distributed import Client

# Start a Dask client (optional, helps in parallel execution)
client = Client()
client  # Displays dashboard link

In [13]:
import os
print(os.listdir())  # Lists all files in the current directory

['.cache', '.conda', '.git', '.gitconfig', '.ipynb_checkpoints', '.ipython', '.jupyter', '.keras', '.matplotlib', '.vscode', 'agree.c', 'anaconda3', 'AppData', 'Application Data', 'Book1.csv', 'car.csv', 'codtech', 'Contacts', 'Cookies', 'COVID_CNN.ipynb', 'Data.csv', 'DAVT', 'DAVT.ipynb', 'deep learning', 'desktop', 'Documents', 'Domain Specific.ipynb', 'Downloads', 'downloads.pdf', 'Favorites', 'flask_lab', 'gradient descent.ipynb', 'Links', 'Local Settings', 'MLBI', 'Moon', 'Music', 'My Documents', 'NetHood', 'NN', 'NTUSER.DAT', 'ntuser.dat.LOG1', 'ntuser.dat.LOG2', 'NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TM.blf', 'NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TMContainer00000000000000000001.regtrans-ms', 'NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TMContainer00000000000000000002.regtrans-ms', 'ntuser.ini', 'OneDrive', 'Oracle', 'pandas.ipynb', 'Pictures', 'Position_Salaries.csv', 'PrintHood', 'PycharmProjects', 'Recent', 'Salary_Data.csv', 'sample exp-4.ipynb', 'Saved Games', 'Searches', 'SendTo', 'SMS Spam.ipynb', 'spam.csv', 'Start Menu', 'Templates', 'Untitled.ipynb', 'Untitled1.ipynb', 'Untitled10.ipynb', 'Untitled11.ipynb', 'Untitled12.ipynb', 'Untitled13.ipynb', 'Untitled14.ipynb', 'Untitled15.ipynb', 'Untitled16.ipynb', 'Untitled17.ipynb', 'Untitled18.ipynb', 'Untitled19.ipynb', 'Untitled2.ipynb', 'Untitled20.ipynb', 'Untitled3.ipynb', 'Untitled4.ipynb', 'Untitled5.ipynb', 'Untitled6.ipynb', 'Untitled7.ipynb', 'Untitled8.ipynb', 'Untitled9.ipynb', 'Urban-Green-Indoor-Hydroponic-Farming-Kits.pdf', 'Videos', 'WPS Cloud Files']

In [21]:
import dask.dataframe as dd

df = dd.read_csv("imdb_top_1000.csv", dtype={'Meta_score': 'float64', 'Released_Year': 'object'})

df.head()  # Now try viewing the data

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

In [22]:
def extract_year(released_year):
    try:
        # Try to convert to int (for years like "2023")
        return int(released_year)
    except ValueError:
        # Handle cases like "PG", "R", etc.  (extract if possible)
        parts = released_year.split(" ") # Split to handle "PG-13" or similar
        for part in parts:
            try:
                return int(part)
            except ValueError:
                pass
        return None  # Or another appropriate value for non-year entries

df['Released_Year'] = df['Released_Year'].map(extract_year, meta=('Released_Year', 'int64')) # Apply the function

df.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994.0,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972.0,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008.0,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974.0,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957.0,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

In [23]:
df['Released_Year'] = df['Released_Year'].fillna(0).astype(int) # Fill NaN values with 0 and convert to int

df.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

In [25]:
print(df["Meta_score"].mean().compute())

77.97153024911032

In [26]:
# Perform basic operations to demonstrate scalability (e.g., calculate mean of a column)
mean_value = df['Meta_score'].mean()

# Trigger computation (compute() performs the actual processing)
result = mean_value.compute()

# Print the result
print(f"Mean value: {result}")

Mean value: 77.97153024911032

In [27]:
import time

# Start time
start_time = time.time()

# Perform the analysis (same as the previous step)
result = mean_value.compute()

# End time
end_time = time.time()

# Print the result and time taken
print(f"Mean value: {result}")
print(f"Time taken: {end_time - start_time} seconds")

Mean value: 77.97153024911032
Time taken: 0.17115020751953125 seconds

In [28]:
from dask.distributed import LocalCluster

# Create a local Dask cluster with more workers (for example, 4 workers)
cluster = LocalCluster(n_workers=4)
client = Client(cluster)

# Perform the same analysis as before
result = mean_value.compute()

# Print result and monitor time
print(f"Mean value: {result}")

C:\Users\esire\anaconda3\lib\site-packages\distributed\node.py:179: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 50799 instead
  warnings.warn(

Mean value: 77.97153024911032

In [30]:
df.info()

<class 'dask.dataframe.core.DataFrame'>
Columns: 16 entries, Poster_Link to Gross
dtypes: object(12), float64(2), int32(1), int64(1)

In [32]:
df.columns

Index(['Poster_Link', 'Series_Title', 'Released_Year', 'Certificate',
       'Runtime', 'Genre', 'IMDB_Rating', 'Overview', 'Meta_score', 'Director',
       'Star1', 'Star2', 'Star3', 'Star4', 'No_of_Votes', 'Gross'],
      dtype='object')

2025-02-06 19:49:36,619 - distributed.scheduler - WARNING - Worker failed to heartbeat within 300 seconds. Closing: <WorkerState 'tcp://127.0.0.1:50535', name: 2, status: running, memory: 0, processing: 0>
2025-02-06 19:49:36,675 - distributed.scheduler - WARNING - Worker failed to heartbeat within 300 seconds. Closing: <WorkerState 'tcp://127.0.0.1:50549', name: 3, status: running, memory: 0, processing: 0>
2025-02-06 19:49:36,697 - distributed.scheduler - WARNING - Worker failed to heartbeat within 300 seconds. Closing: <WorkerState 'tcp://127.0.0.1:50831', name: 2, status: running, memory: 0, processing: 0>
2025-02-06 19:49:36,704 - distributed.scheduler - WARNING - Worker failed to heartbeat within 300 seconds. Closing: <WorkerState 'tcp://127.0.0.1:50837', name: 1, status: running, memory: 0, processing: 0>
2025-02-06 19:49:37,136 - distributed.scheduler - WARNING - Received heartbeat from unregistered worker 'tcp://127.0.0.1:50535'.
2025-02-06 19:49:37,144 - distributed.scheduler - WARNING - Received heartbeat from unregistered worker 'tcp://127.0.0.1:50549'.
2025-02-06 19:49:37,157 - distributed.scheduler - WARNING - Received heartbeat from unregistered worker 'tcp://127.0.0.1:50837'.
2025-02-06 19:49:37,194 - distributed.scheduler - WARNING - Received heartbeat from unregistered worker 'tcp://127.0.0.1:50831'.

In [34]:
from dask.distributed import LocalCluster

# Create a local Dask cluster with more workers (for example, 4 workers)
cluster = LocalCluster(n_workers=4)
client = Client(cluster)

# Perform the same analysis as before
result = mean_value.compute()

# Print result and monitor time
print(f"Mean value: {result}")

C:\Users\esire\anaconda3\lib\site-packages\distributed\node.py:179: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 51343 instead
  warnings.warn(

Mean value: 77.97153024911032

In [35]:
# Filter the dataset where column 'column_name' > 50
filtered_df = df[df['No_of_Votes'] > 50]

# Calculate the mean of 'another_column' after filtering
mean_filtered_value = filtered_df['IMDB_Rating'].mean()

# Trigger computation
result_filtered = mean_filtered_value.compute()

# Print the result
print(f"Filtered mean value: {result_filtered}")

Filtered mean value: 7.949299999999999

In [36]:
# Increase dataset size by loading a bigger file or partitioning it
df = dd.read_csv("imdb_top_1000.csv", blocksize=25e6)  # 25 MB per partition

# Perform the same computation again to see scaling performance
result = mean_value.compute()
print(f"Mean value for larger dataset: {result}")

Mean value for larger dataset: 77.97153024911032